### ISSUE TITLE
Convert an existing Stream into deluge

### ISSUE THREAD

**Issue by arlyon** [mkawalec/deluge#10]
Hi!

I have a stream that I cannot control that I would like to operate over in parallel. What options do I have here?

Cheers

Alex

**Comment by mkawalec** [comment]
Hey @arlyon! A `Stream` would only give out a single evaluated element at a time (see the `poll_next` method [on the `Stream`](https://docs.rs/futures/latest/futures/stream/trait.Stream.html)). This means that it's construction itself blocks us from evaluating it in parallel. If you want to do further processing that itself is async, I would suggest collecting the stream into a vector, using [`into_deluge` on that vector](https://docs.rs/deluge/latest/deluge/trait.IntoDeluge.html) and performing some async transformations on the resultant `Deluge` in a similar fashion to [what the docs show](https://docs.rs/deluge/latest/deluge/index.html). 

Is this helpful?

**Comment by arlyon** [comment]
I was imagining something like rayon's `par_bridge` which I assume eagerly collects items into an intermediary ringbuffer before sending them out to threads. Less efficient than starting with a collection in memory, but is able to handle 'very large' datasets much easier.

https://docs.rs/rayon/latest/rayon/iter/trait.ParallelBridge.html

**Comment by mkawalec** [comment]
Good idea, I'll add something similar to the todolist, that converts a `Stream` into a `Deluge` without materializing the whole intermediate dataset. Of course you are encouraged to contribute it yourself if you have the capacity.

**Comment by mkawalec** [comment]
Closing because I don't believe there is a straightforward way to convert a stream into a `Deluge` given that a `Deluge` needs to know how many elements it is going to have when it is being created. But I'll keep on thinking about it :)
